version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: Queue
    hostname: localhost
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
